<?php echo $this->form ?>

<?php echo $this->renderSmallTools($this->tools); ?>

<div id="syslog" style="overflow: scroll; white-space: pre;">
<?php echo $this->content; ?>
</div>

<script>
    var reloadSysLog = function() {
        Jsw.submit('<?php echo $this->form->getId() ?>');
    };

    Jsw.onReady(function() {
        var syslog = $('syslog');
        var resizeBlock = function() {
            var bodyHeight = $(document.body).getHeight();
            var blockTop = Position.cumulativeOffset(syslog).top;
            var blockBottom = $('footer-wrapper') ? $('footer-wrapper').getHeight() : 0;
            syslog.setStyle({ 'max-height': (bodyHeight - blockTop - blockBottom) + 'px' });
        };
        resizeBlock();
        Event.observe(window, 'resize', resizeBlock);

        var total = <?php echo (int)$this->total ?>;
        var inProgress = false;
        var appendLog = function() {
            if (inProgress || !$('autoUpdate').checked) {
                return;
            }

            new Ajax.Request('<?php echo pm_Context::getActionUrl('index', 'data') ?>', {
                method: 'post',
                parameters: { from: total },
                onCreate: function() {
                    inProgress = true;
                },
                onComplete: function() {
                    inProgress = false;
                },
                onSuccess: function(transport) {
                    var logData = transport.responseText;
                    logData = logData.strip();
                    var logDataLines = logData.split("\n", 2);
                    total = parseInt(logDataLines[0]);
                    var content = logDataLines[1];
                    if (content.length) {
                        content = "\n" + content;
                        syslog.insert({ bottom: content });
                    }
                }
            });
        };
        setInterval(appendLog, 1000);
    });
</script>