#!/bin/sh
### Copyright 1999-2014. Parallels IP Holdings GmbH. All Rights Reserved.

LINES=$1
FROM=$2

if [ -f /var/log/syslog ]
then
  SYSLOG=/var/log/syslog
else
  SYSLOG=/var/log/messages
fi

TOTAL=$(wc -l $SYSLOG | awk '{print($1)}')
echo $TOTAL

if [ ! -z $FROM ]
then
    LINES=$(( TOTAL - FROM ))
fi

tail -n $LINES $SYSLOG
